name: "New Relic Synthetics via Terraform"

on:
  push:
    branches:
      - main
    paths:
      - 'teams/**'      # Only run if a team YAML file changes
      - 'terraform/**'  # Or if the terraform logic changes
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Action"
    runs-on: ubuntu-latest
    
    # Environment variables for New Relic Provider
    env:
      TF_VAR_NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
      TF_VAR_NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
      TF_VAR_NEW_RELIC_REGION: "US" # or "EU"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: ./terraform

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color
        working-directory: ./terraform

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
        working-directory: ./terraform